### ISSUE TITLE
Retrieving the parameter values that led to a derived parameter

### ISSUE THREAD

**Issue by EdwMo** [amosborne/worstcase#1]
Hi amosborne
First of all thank you for sharing this tool. I believe it has an enormous potential.
I was wondering if there is a possibility to retrieve the bondaries on the parameters that led to your derived parameter. 

In your examble would be the specific values of R1 to R5 and VOS that led to the WC value of the VOUT_1A upper and lower bounds. 

I've been trying to retrieve the eval_init dictionary created in the call to the function " extreme_value" but I believe there have to be cleaner ways of doing it.

Help here, or adding this feature would be highly appreciated.

Regards

**Comment by amosborne** [comment]
Hello, I appreciate the compliment. I think you're on the right track by using the 'eval_init' dictionary. Let me see what I can do.

I'm curious to know what you may be using this software for?

**Comment by amosborne** [comment]
I've updated the code such that when a parameter is derived using the `byev` method, the resulting parameter has a field called `derivation`. This field has subfields `nom`, `lb`, and `ub`, which are dictionaries of the parameters used to make the derivation and the exact value used. Please let me know if this addresses your request.

[I've included the example outputs in the example python notebook (see cells 6 and 13).](https://github.com/amosborne/worstcase/blob/master/example.ipynb)

**Comment by EdwMo** [comment]
Hey, thanks for the quick implementation, that is actually exactly what I meant. 

Regarding the usage to give to it. I am also an electronic engineer working in aerospace :). I was about gonna start writing my own WC "calculator", (a very reduced version of your tool, mostly just for corner cases by brute force ) when I came across your code, so started digging around. Got a bit lost with the usage of the networkx library and your data structure, but I find the code is written in a pretty smart style. Finally for the type of circuitry I'm dealing with I think maybe is an overkill (not much complex analog stages), but I'll keep it around to see how much of the WCA process I can  automatize with it. I'll keep you posted

**Comment by amosborne** [comment]
Great! Nice to hear. Best of luck.
